color1= input('Please enter Color 1: ')
color2= input('Please enter Color 2: ')
if (color1 == 'red'and color2 =='blue') or (color1 == 'blue' and color2 == 'red')
    print (f'Your secondary color is PURPLE.')
elif (color1 == 'red' and color2 == 'yellow') or (color1== "yellow ")
    print(f'Your secondary color is ORANGE')
elif (color1 == 'red' and color2 == 'yellow') or (color1== "yellow ")
    print(f'Your secondary color is GREEN')
elif (color1 == 'blue' and color2 == 'yellow') or (color1== "yellow ")
    print(f'Your secondary color is ORANGE')
